services:

  Apps.amongUs.controllers.UsersGetController:
    class: ../../controllers/UsersGetController
    arguments: ['@AmongUs.users.application.GetUsers']
  
  Apps.amongUs.controllers.UsersPostController:
    class: ../../controllers/UsersPostController
    arguments: ['@AmongUs.users.application.CreateUser']

  Apps.amongUs.controllers.UsersDeleteController:
    class: ../../controllers/UsersDeleteController
    arguments: ['@AmongUs.users.application.DeleteUser']

  Apps.amongUs.controllers.KillsGetController:
    class: ../../controllers/KillsGetController
    arguments: ['@AmongUs.kills.application.GetKills']

  Apps.amongUs.controllers.KillsPostController:
    class: ../../controllers/KillsPostController
    arguments: ['@AmongUs.kills.application.CreateKill']

  Apps.amongUs.controllers.KillsDeleteController:
    class: ../../controllers/KillsDeleteController
    arguments: ['@AmongUs.kills.application.DeleteKill']

  Apps.amongUs.controllers.InitGameController:
    class: ../../controllers/InitGameController
    arguments: ['@AmongUs.game.application.InitGame']
