services:


  AmongUs.NodeMailerConfig:
    factory:
      class: ../../../../../contexts/among-us/_shared/infrastructure/mailer/nodemailer/NodeMailerConfigFactory
      method: 'createConfig'

  AmongUs.mailer.ConnectionManager:
    factory:
      class: ../../../../../contexts/_shared/infrastructure/mailer/nodemailer/NodeMailerSender
      method: 'createClient'
    arguments: ['@AmongUs.NodeMailerConfig']

  AmongUs.game.domain.SendEmailInitGame:
    class: ../../../../../contexts/among-us/game/infrastructure/mailer/NodeMailerSendEmailInitGame
    arguments: [AmongUs.Mailer.ConnectionManager]

  AmongUs.MongoConfig:
    factory:
      class: ../../../../../contexts/among-us/_shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  AmongUs.ConnectionManager:
    factory:
      class: ../../../../../contexts/_shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['among-us', '@AmongUs.MongoConfig']

  AmongUs.game.domain.UserRepository:
    class: ../../../../../contexts/among-us/game/infrastructure/persistence/MongoUserRepository
    arguments: ['@AmongUs.ConnectionManager']

  AmongUs.game.domain.KillRepository:
    class: ../../../../../contexts/among-us/game/infrastructure/persistence/MongoKillRepository
    arguments: ['@AmongUs.ConnectionManager']

  AmongUs.game.application.InitGame:
    class: ../../../../../contexts/among-us/game/application/InitGame
    arguments: [
      '@AmongUs.game.domain.UserRepository',
      '@AmongUs.game.domain.KillRepository',
      '@AmongUs.game.domain.SendEmailInitGame'
    ]

